name: 'punktlich_dbt'
version: '1.0.0'
config-version: 2

profile: 'punktlich_data_platform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  punktlich_dbt:
    silver:
      +materialized: view  
    gold:
      +materialized: table 